version: '2'
services:
  customer-api:
    build: ./customer/.
    command: npm run start
    ports:
      - "3000:3000"
  invoice-api:
    build: ./invoice/.
    command: npm run start
    ports:
      - "3001:3001"
  graphql-gateway:
    build: ./graphql-gateway/.
    environment:
      - CUSTOMER_API_URL=http://customer-api:3000/customer-api/swagger
      - INVOICE_API_URL=http://invoice-api:3001/invoice-api/swagger
    command: npm run start
    ports:
      - "5000:5000"
    depends_on:
      - customer-api
      - invoice-api

